name: Slides Builder

on:
    push:
        branches:
            - master
jobs:
    Slide-Publisher:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install Node.js, NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 14
            - name: "Install Yarn"
              run: npm install -g yarn
            - name: "Install Dependencies"
              run: yarn
            - name: "Install playwright-chromium"
              run: yarn add playwright-chromium
            - name: "Build"
              run: yarn run base-build
            - name: Commit files
              continue-on-error: true
              run: |
                  ls dist
                  ls docs
                  cat .gitignore
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  rm -rf docs
                  mv dist docs
                  git add -A
                  git commit -m "test" -a
            - name: "Push changes"
              uses: ad-m/github-push-action@master
              continue-on-error: true
              with:
                  github_token: ${{ secrets.RELEASE_TOKEN }}
